### PR TITLE
Reformat the github workflows config, add crates.io deploy stage

### PR DESCRIPTION
**Pull request by crsaracco**
No clue if the deploy thing actually works, but it should be close? :upside_down_face:

### CODE REVIEW

**Review by askeksa — COMMENTED** [review]
Looks sensible, though it seems to be missing the documentation part of the original deploy script. Is this something we need in order to have the documentation link on crates.io point to the right thing, or will that happen automatically on `cargo publish`?

**Comment by crsaracco** [comment]
So, for **releases**, we seem to automatically get documentation built for us -- https://docs.rs/vst/0.2.0/vst/ exists, even though I don't see us setting that up anywhere (my guess is that it's generated on publish to crates.io). IMO we should use that link instead of our manually generated one for crates.io.

For **development**, it makes sense to me to keep using our own manually generated docs on push to master, so that people can click a link in the readme and read that if needed.

Although that may create a little bit of confusion, so we should probably make it clearer which one's which in the readme.

I'll go:
 - see if I can create a GH action for generating the docs
 - see if I can change the link on crates.io
 - update the readme if the above two work

**Review by askeksa — APPROVED** [review]
Looks good, let's try and see. ;)

**Comment by crsaracco** [comment]
Ok, so results:

 - The GH action for generating the documents for the `master` branch seems to work on my fork (which is surprising to me, since I don't have `secrets.GH_ENCRYPTED_TOKEN` set up on my fork -- maybe we don't need that secret at all?)
 - crates.io just uses the `documentation` field in `Cargo.toml`, so I removed it (it will [default to docs.rs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field)).
 - Updated `README.md` to link to both versions of documentation, depending on the user's use case

**Pull request merged**
