### PR TITLE
Allow plug-in to return a custom value in can_do()

### PR DESCRIPTION
**Pull request by helgoboss**
Background: [Cockos Extensions to VST SDK](http://reaper.fm/sdk/vst/vst_ext.php) defines some non-standard behavior controlled via custom `can_do()` return values (other than 1, 0 or -1). I'm currently using this in [ReaLearn](https://github.com/helgoboss/realearn/blob/a7ccda9f5bd27738b40e15f084dfaacc671b299f/src/infrastructure/plugin/realearn_plugin.rs#L119).

### CODE REVIEW

**Comment by helgoboss** [comment]
Is there anything missing to get this merged? Seems like the Travis build got stuck.

**Comment by Boscop** [comment]
Apparently Travis build failed here (due to formatting): https://travis-ci.org/github/RustAudio/vst-rs/jobs/702150434#L363

**Comment by helgoboss** [comment]
@Boscop Ah, thanks. Will look into it. I was confused by the "Waiting for status to be reported" message.

**Comment by Boscop** [comment]
It failed again:
```
The command "cargo test --verbose" exited with 0.
0.91s$ cargo fmt --all -- --check
Diff in /home/travis/build/RustAudio/vst-rs/src/api.rs at line 256:
     Yes,
     Maybe,
     No,
-    Custom(isize)
+    Custom(isize),
 }
 
 impl Supported {
Diff in /home/travis/build/RustAudio/vst-rs/src/api.rs at line 282:
             Yes => 1,
             Maybe => 0,
             No => -1,
-            Custom(i) => i
+            Custom(i) => i,
         }
     }
 }
The command "cargo fmt --all -- --check" exited with 1.
```
Rustfmt requires all enum variants to have commas afterwards.

**Comment by helgoboss** [comment]
Thanks, I haven't yet made any attempt to fix it.

**Comment by helgoboss** [comment]
@Boscop Worked day and night on adding the comma. Now it's finished ;)

**Pull request merged**
