### PR TITLE
Replace transmute with just pointer cast

### PR DESCRIPTION
**Pull request by faern**
As the docs say, transmutes can easily cause undefined behavior and should be a last resort. After running `clippy` on this crate I saw that most of the transmutes here were basically just pointer casts. So I replaced them with pointer casts. Should produce the exact same result, but in a way that makes it easier for the compiler to spot invalid usage.

However, `clippy` is warning about dangerous casts between differently aligned pointers. Two of these already existed in the code base and one came up with this PR. However, I think the one introduced now is not a new problem, it probably existed when that cast was a transmute as well, just that clippy could not spot it(?). I don't know enough about VST or this code base yet to tell if this is dangerous or not, but clippy has this to say about it:
```
error: casting from `*const api::Event` to a more-strictly-aligned pointer (`*const api::SysExEvent`)
   --> src/event.rs:117:53
    |
117 |                     let event: &api::SysExEvent = &*(&event as *const _ as *const api::SysExEvent);
    |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.207/index.html#cast_ptr_alignment
```

### CODE REVIEW

**Comment by faern** [comment]
The git history of this turned crazy. So I just rebased it. The main parts of this PR is already in master now, so it now has less content, but anyway.

**Comment by crsaracco** [comment]
Is there anything left to be done here? If not, I'm going to work on merging this in after we merge in all of the PRs newer than this one.

**Comment by faern** [comment]
@crsaracco I don't have anything to add. This is ready to merge for me.

**Comment by crsaracco** [comment]
Merged all of the latest commits into this branch, and I'm not seeing the clippy warning from the original message when running `cargo +stable clippy`:

```
error: casting from `*const api::Event` to a more-strictly-aligned pointer (`*const api::SysExEvent`)
   --> src/event.rs:117:53
    |
117 |                     let event: &api::SysExEvent = &*(&event as *const _ as *const api::SysExEvent);
    |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.207/index.html#cast_ptr_alignment
```

So... I guess it went away? :metal: Merging this PR now.

I'm going to make another PR pretty soon fixing the other clippy stuff, and maybe also making the clippy (and formatting) checks a little more strict.

**Pull request merged**
