### PR TITLE
Implement FromStr for CanDo (closes  #110)

### LINKED ISSUE #10: Add a more advanced host example
It took me some time to get [this](https://github.com/Bobo1239/rust-vst-demo) to work. (And I'm not sure if that's the intended usage.) Adding a host example which utilizes `AudioBuffers` and `(Midi)Event`s would make this aspect of the project more approachable.

### LINKED ISSUE #110: Implement FromStr for CanDo
Clippy identified that we should implement the `FromStr` trait for `CanDo` instead of just [making our own `from_str` function](https://github.com/RustAudio/vst-rs/blob/aa7cc43daac810be800741a96a38dea89c8cf25b/src/plugin.rs#L411).

This decision came out of #104, but I didn't want to do it there because it is a slight function signature change. I think it should be pretty easy though.

### PR DESCRIPTION
**Pull request by inikulin**

### CODE REVIEW

**Comment by crsaracco** [comment]
Looks fine to me, basically does the same thing but gets rid of the clippy warning.

I remember @askeksa and I talking about if we really wanted to make this change, so I'll let him weigh in as well.

**Comment by crsaracco** [comment]
Hmm, it's marked as `pub`. If users aren't expected to use it, we could instead remove the `pub` and call it a day.

If it's left `pub`, I can see why clippy would complain: if users see a `from_str` method implemented (perhaps in an IDE autocomplete or something), they might expect the entire trait to be implemented. In that case, maybe we could just rename it to something else?

Overall I'm rather indifferent, and I'm fine with leaving it as-is.

I don't think it should return an error for a good (`Other`) value, and assuming `s: &str` is a valid string it should always succeed.

Side-note: It looks to me like `read_string` in `interfaces.rs` should be marked `unsafe`. I vaguely remember a discussion a long time ago about why it isn't? We should add a comment there discussing why it's not `unsafe` if so.

**Comment by inikulin** [comment]
@askeksa 
> I find it weird to return a Result type from a function that never fails and then wrap a type that has its own built-in fallback case (the Other variant).

When never type will be stabilised it can be rewritten to `Result<Self, !>`. Though I don't really have any preferences with this PR. Feel free to close it, just wanted to clean up the issues a bit.

**Comment by askeksa** [comment]
Closing this until we get a compelling reason to do the change.

**Pull request closed without merging**
