### PR TITLE
Ensure that Outputs cannot be cloned.

### LINKED ISSUE #66: Outputs API allows for multiple references as mutable to the same data.
The `Outputs` struct has two ways in which you can get multiple references as mutable to the same data:

1. The `Outputs` struct can be cloned (it implements the `Clone` trait). When the `get_mut()` method is called on the clone and the original, both give a slice as mutual to the same data. 

2. The `Outputs::split_at_mut()` method can be called more than once on the same instance, resulting in different `Outputs` that refer to the same data.

### PR DESCRIPTION
**Pull request by PieterPenninckx**
Closes #66 

I did four things to solve the issue mentioned in #66 :

1. I removed the `#[derive(Copy, Clone)]` attribute from `Outputs`.
2. I changed the signature of the `Outputs::split_at_mut` method so that it takes an `self` parameter instead of `&mut self`. So calling `split_at_mut` will now move instead of "borrow". This is not as ergonomic as the previous API. Another way to solve the problem is to instead change the return type as follows: ```pub fn split_at_mut<'b>(&'b mut self, i: usize) -> (OutputsPart<'a, 'b, T>, OutputsPart<'a, 'b, T>)``` where `OutputsPart` is a newly defined struct. Let me know if you prefer this alternative instead.
3. Because `Outputs` is not a copy type anymore after the first change, the `into_iter()` method was not ergonomic anymore (because it required ownership). So I changed the code. Now `&mut Outputs` (instead of `Outputs`) implements the `IntoIterator` trait. This allows you to still call `into_iter()` when you merely borrow an `Outputs` (as opposed to owning it).
4. The third change required some changes to the `AudioBuffer::zip()` method (the previous implementation required `AudioBuffer` to be split into `Inputs` and `Outputs`, but the iterator over `Outputs` now borrows `Outputs`, so we cannot return it because the `Outputs` does not outlive the `zip` method).

These are breaking changes.

### CODE REVIEW

**Comment by piedoom** [comment]
Is this still WIP or is this a candidate for merging?

**Comment by PieterPenninckx** [comment]
> Is this still WIP or is this a candidate for merging?

I am quite confident that the general idea works and is ergonomic enough, but I would like to add some tests for the edge cases of the `AudioBufferIterator`, so in my eyes it's still a WIP.

**Comment by PieterPenninckx** [comment]
I have added the tests for the `zip()` method. I think this can be merged (after an approving review).

**Comment by PieterPenninckx** [comment]
Oops, I was too quick to say this could be merged. There were some unnecessary lifetime bounds. These are no problem for "normal usage" (like plugins), but they made it hard to build a higher level abstraction layer on top of `rust-vst`. (And then I removed too many bounds. Ok for Rust nightly, not for stable. I re-inserted enough bounds to make the compiler happy again and also to enable higher-level abstractions.)

**Comment by crsaracco** [comment]
Is there anything left to be done here? If not, I'm going to work on merging this in after we merge in all of the PRs newer than this one.

**Comment by PieterPenninckx** [comment]
This is done and can be merged.

**Pull request merged**
